baseURL: "https://jellyfin.org"
languageCode: en-us
disableKinds:
  - '404'
title: "Jellyfin: The Free Software Media System"
markup:
  goldmark:
    renderer:
      unsafe: true
permalinks:
  post: "/post/:year/:month/:day/:slug/"
  note: "/note/:year/:month/:day/:slug/"
menus:
  main:
    - name: Blog
      Url: /posts
      weight: 1
    - name: Clients
      Url: /clients
      weight: 2
    - name: Download
      Url: /download
      weight: 3
    - name: Contribute
      Url: /contribute
      weight: 4
    - name: Documentation
      Url: https://docs.jellyfin.org
      weight: 5
    - name: Contact
      Url: /contact
      weight: 6
outputs:
  posts:
    - HTML
    - RSS
params:
  author: "The Jellyfin Team"
  footer:
    firstcolumn:
      - Site content is licensed [CC-BY-ND-4.0](http://creativecommons.org/licenses/by-nd/4.0/)
      - Website hosted on [GitHub](https://github.com/jellyfin/jellyfin-blog)
    secondcolumn:
      -
    thirdcolumn:
      - Check us out on [GitHub](https://github.com/jellyfin)
      - See our [Documentation](/docs/)
