baseURL: "https://jellyfin.org/"
languageCode: en-us
title: "Jellyfin: The Free Software Media System"

markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
  post: "/post/:year/:month/:day/:slug/"
  note: "/note/:year/:month/:day/:slug/"
menus:
  main:
    - name: Blog
      Url: /posts
      weight: 1
    - name: Downloads
      Url: /downloads
      weight: 2
    - name: How To Contribute
      Url: /contribute
      weight: 3
    - name: Get Help
      Url: /docs
      weight: 4
    - name: Contact Us/Links
      Url: /contact
      weight: 5
params:
  author: "The Jellyfin Team"
  footer:
    firstcolumn:
      - Site content is licensed [CC-BY-ND-4.0](http://creativecommons.org/licenses/by-nd/4.0/)
      - Website hosted on [GitHub](https://github.com/jellyfin/jellyfin.github.io)
    secondcolumn:
      -
    thirdcolumn:
      - Check us out on [Github](https://github.com/jellyfin)
      - See our [documentation](/docs/)
