trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
- job: Build
  displayName: 'Build'

  pool:
    vmImage: windows-latest

  steps:
  - task: HugoTask@1
    displayName: 'Build Website'
    inputs:
      source: '$(Build.SourcesDirectory)'
      destination: '$(Build.SourcesDirectory)/public'
      hugoVersion: '0.60.1'
      extendedVersion: true

  - task: ArchiveFiles@2
    displayName: 'Archive Website'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/public'
      includeRootFolder: true
      archiveFile: '$(Build.ArtifactStagingDirectory)/jellyfin-blog-$(Build.BuildId)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Docs'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'jellyfin-blog-$(Build.BuildId)'
      publishLocation: 'Container'

- job: Publish
  displayName: 'Publish'

  dependsOn: Build
  condition: and(contains(variables['Build.SourceBranch'], 'master'), notIn(variables['Build.Reason'], 'PullRequest'))

  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: none

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Artifact'
    inputs:
      source: 'current'
      artifact: 'jellyfin-blog-$(Build.BuildId)'
      path: '$(Build.SourcesDirectory)'
      runVersion: 'latest'

  - task: DownloadSecureFile@1
    displayName: 'Download GitHub Key'
    name: 'Bot'
    inputs:
      secureFile: 'bot'

  - task: Bash@3
    displayName: 'Update Website'
    inputs:
      targetType: 'filePath'
      filePath: '.ci/publish-to-gh-pages.sh'
      workingDirectory: '$(Build.SourcesDirectory)'
      failOnStderr: true
