name: '🏗️ Build jellyfin-blog'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/*.json'

jobs:
  build:
    uses: jellyfin/jellyfin-blog/.github/workflows/_meta.yaml@master
    with:
      publish: false
